name: "Design Handoff"
description: Hand off approved designs to the HTML/CSS core development team.
title: "[Design]: "
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for the handoff! 
        Please provide the following details to help the HTML/CSS team build the components accurately.

  - type: input
    id: figma-link
    attributes:
      label: Figma Link
      description: Link to the specific frame or page in Figma. It should have a "before" screen and an "after" screen for the dev to easily see the changes they need to implement.
      placeholder: "https://www.figma.com/file/..."
    validations:
      required: true

  - type: input
    id: jira-ticket
    attributes:
      label: Jira/GitHub Ticket Link
      description: Link to the original design/request ticket.
      placeholder: "https://..."
    validations:
      required: true

  - type: textarea
    id: design-preview
    attributes:
      label: Design Screenshot
      description: |
        Please paste a screenshot of the design here. This provides a quick reference within the issue.
        (Tip: You can drag and drop or paste images directly into this box).
      placeholder: "Paste image here..."
    validations:
      required: true

  - type: textarea
    id: technical-specs
    attributes:
      label: Any extra notes for developers
      description: |
        Please highlight any key changes the developers should be looking out for- plus extra hand off notes you'd like to provide.
      placeholder: "Explain variants, hover states, transitions, or responsive behavior..."
