#!/usr/bin/env bash

pf add:component PfAccordion
pf add:component PfAlert
pf add:component PfAnalytics
pf add:component PfAvatar
pf add:component PfBadge
pf add:component PfBanner
pf add:component PfBlanket
pf add:component PfBox
pf add:component PfBreadcrumb
pf add:component PfButton
pf add:component PfButtonGroup
pf add:component PfCalendar
pf add:component PfCard
pf add:component PfCarousel
pf add:component PfCheckbox
pf add:component PfCodeSnippet
pf add:component PfCollapse
pf add:component PfComment
pf add:component PfContent
pf add:component PfContentSwitcher
pf add:component PfDataTable
pf add:component PfDatePicker
pf add:component PfDelete
pf add:component PfDropdown
pf add:component PfDropdownMenu
pf add:component PfDynamic Table
pf add:component PfFieldRange
pf add:component PfFile
pf add:component PfFileUploader
pf add:component PfFlag
pf add:component PfForm
pf add:component PfFormControl
pf add:component PfGauge
pf add:component PfIcon
pf add:component PfImage
pf add:component PfInlineDialog
pf add:component PfInlineEdit
pf add:component PfInlineMessage
pf add:component PfInput
pf add:component PfInputGroup
pf add:component PfJumbotron
pf add:component PfLayerManager
pf add:component PfLineGraph
pf add:component PfLink
pf add:component PfList
pf add:component PfListGroup
pf add:component PfLoading
pf add:component PfLogo
pf add:component PfLozenge
pf add:component PfMenu
pf add:component PfMessage
pf add:component PfModal
pf add:component PfModalDialog
pf add:component PfMultiSelect
pf add:component PfNav
pf add:component PfNavbar
pf add:component PfNavigation
pf add:component PfNotification
pf add:component PfNumberInput
pf add:component PfOverflowMenu
pf add:component PfPage
pf add:component PfPageHeader
pf add:component PfPagination
pf add:component PfPanel
pf add:component PfPieChart
pf add:component PfPopover
pf add:component PfProgress
pf add:component PfProgressIndicator
pf add:component PfRadio
pf add:component PfRadioButton
pf add:component PfRadioGroup
pf add:component PfScatterPlot
pf add:component PfScrollspy
pf add:component PfSearch
pf add:component PfSelect
pf add:component PfSingleSelect
pf add:component PfSlider
pf add:component PfSpinner
pf add:component PfStructuredList
pf add:component PfTable
pf add:component PfTabs
pf add:component PfTag
pf add:component PfTagGroup
pf add:component PfTextarea
pf add:component PfTextField
pf add:component PfTextFieldArea
pf add:component PfTextInput
pf add:component PfTheme
pf add:component PfTile
pf add:component PfTitle
pf add:component PfToggle
pf add:component PfTooltip
