name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '37 11 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: -1
          exempt-issue-labels: 'accessibility,breaking change,design approved,pinned'
          stale-issue-label: 'stale'
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had activity in the last 60 days.'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had activity in the last 60 days.'
