name: pr-preview
on: pull_request_target
jobs:
  build-upload:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
      GH_PR_NUM:   ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v2
      # Yes, we really want to checkout the PR
      - run: |
          git rev-parse HEAD
          git rev-parse origin/main

      - run: |
          git fetch origin pull/$GH_PR_NUM/head:tmp
          git checkout tmp

      - run: |
          git rev-parse HEAD
          git rev-parse origin/main
          if git log origin/main..HEAD --format="%b" | grep -i "breaking change";
          then
              echo "Breaking change detected in commit message"
              exit 1
          fi

        name: Breaking change lint
        if: always()
      # Injected by generate-workflows.js
      %build-test%

